<?php
/**
 * Created by PhpStorm.
 * User: charles
 * Date: 2019/4/29
 * Time: 下午2:25
 */

/**
 * 以下常量只在 php-rdkafka 扩展启用时，在运行时有效
 */

$constants = [
    'RD_KAFKA_CONSUMER',
    'RD_KAFKA_OFFSET_BEGINNING',
    'RD_KAFKA_OFFSET_END',
    'RD_KAFKA_OFFSET_STORED',
    'RD_KAFKA_PARTITION_UA',
    'RD_KAFKA_PRODUCER',
    'RD_KAFKA_VERSION',
    'RD_KAFKA_RESP_ERR__BEGIN',
    'RD_KAFKA_RESP_ERR__BAD_MSG',
    'RD_KAFKA_RESP_ERR__BAD_COMPRESSION',
    'RD_KAFKA_RESP_ERR__DESTROY',
    'RD_KAFKA_RESP_ERR__FAIL',
    'RD_KAFKA_RESP_ERR__TRANSPORT',
    'RD_KAFKA_RESP_ERR__CRIT_SYS_RESOURCE',
    'RD_KAFKA_RESP_ERR__RESOLVE',
    'RD_KAFKA_RESP_ERR__MSG_TIMED_OUT',
    'RD_KAFKA_RESP_ERR__PARTITION_EOF',
    'RD_KAFKA_RESP_ERR__UNKNOWN_PARTITION',
    'RD_KAFKA_RESP_ERR__FS',
    'RD_KAFKA_RESP_ERR__UNKNOWN_TOPIC',
    'RD_KAFKA_RESP_ERR__ALL_BROKERS_DOWN',
    'RD_KAFKA_RESP_ERR__INVALID_ARG',
    'RD_KAFKA_RESP_ERR__TIMED_OUT',
    'RD_KAFKA_RESP_ERR__QUEUE_FULL',
    'RD_KAFKA_RESP_ERR__ISR_INSUFF',
    'RD_KAFKA_RESP_ERR__NODE_UPDATE',
    'RD_KAFKA_RESP_ERR__SSL',
    'RD_KAFKA_RESP_ERR__WAIT_COORD',
    'RD_KAFKA_RESP_ERR__UNKNOWN_GROUP',
    'RD_KAFKA_RESP_ERR__IN_PROGRESS',
    'RD_KAFKA_RESP_ERR__PREV_IN_PROGRESS',
    'RD_KAFKA_RESP_ERR__EXISTING_SUBSCRIPTION',
    'RD_KAFKA_RESP_ERR__ASSIGN_PARTITIONS',
    'RD_KAFKA_RESP_ERR__REVOKE_PARTITIONS',
    'RD_KAFKA_RESP_ERR__CONFLICT',
    'RD_KAFKA_RESP_ERR__STATE',
    'RD_KAFKA_RESP_ERR__UNKNOWN_PROTOCOL',
    'RD_KAFKA_RESP_ERR__NOT_IMPLEMENTED',
    'RD_KAFKA_RESP_ERR__AUTHENTICATION',
    'RD_KAFKA_RESP_ERR__NO_OFFSET',
    'RD_KAFKA_RESP_ERR__END',
    'RD_KAFKA_RESP_ERR_UNKNOWN',
    'RD_KAFKA_RESP_ERR_OFFSET_OUT_OF_RANGE',
    'RD_KAFKA_RESP_ERR_INVALID_MSG',
    'RD_KAFKA_RESP_ERR_UNKNOWN_TOPIC_OR_PART',
    'RD_KAFKA_RESP_ERR_INVALID_MSG_SIZE',
    'RD_KAFKA_RESP_ERR_LEADER_NOT_AVAILABLE',
    'RD_KAFKA_RESP_ERR_NOT_LEADER_FOR_PARTITION',
    'RD_KAFKA_RESP_ERR_REQUEST_TIMED_OUT',
    'RD_KAFKA_RESP_ERR_BROKER_NOT_AVAILABLE',
    'RD_KAFKA_RESP_ERR_REPLICA_NOT_AVAILABLE',
    'RD_KAFKA_RESP_ERR_MSG_SIZE_TOO_LARGE',
    'RD_KAFKA_RESP_ERR_STALE_CTRL_EPOCH',
    'RD_KAFKA_RESP_ERR_OFFSET_METADATA_TOO_LARGE',
    'RD_KAFKA_RESP_ERR_NETWORK_EXCEPTION',
    'RD_KAFKA_RESP_ERR_GROUP_LOAD_IN_PROGRESS',
    'RD_KAFKA_RESP_ERR_GROUP_COORDINATOR_NOT_AVAILABLE',
    'RD_KAFKA_RESP_ERR_NOT_COORDINATOR_FOR_GROUP',
    'RD_KAFKA_RESP_ERR_TOPIC_EXCEPTION',
    'RD_KAFKA_RESP_ERR_RECORD_LIST_TOO_LARGE',
    'RD_KAFKA_RESP_ERR_NOT_ENOUGH_REPLICAS',
    'RD_KAFKA_RESP_ERR_NOT_ENOUGH_REPLICAS_AFTER_APPEND',
    'RD_KAFKA_RESP_ERR_INVALID_REQUIRED_ACKS',
    'RD_KAFKA_RESP_ERR_ILLEGAL_GENERATION',
    'RD_KAFKA_RESP_ERR_INCONSISTENT_GROUP_PROTOCOL',
    'RD_KAFKA_RESP_ERR_INVALID_GROUP_ID',
    'RD_KAFKA_RESP_ERR_UNKNOWN_MEMBER_ID',
    'RD_KAFKA_RESP_ERR_INVALID_SESSION_TIMEOUT',
    'RD_KAFKA_RESP_ERR_REBALANCE_IN_PROGRESS',
    'RD_KAFKA_RESP_ERR_INVALID_COMMIT_OFFSET_SIZE',
    'RD_KAFKA_RESP_ERR_TOPIC_AUTHORIZATION_FAILED',
    'RD_KAFKA_RESP_ERR_GROUP_AUTHORIZATION_FAILED',
    'RD_KAFKA_RESP_ERR_CLUSTER_AUTHORIZATION_FAILED',
    'RD_KAFKA_CONF_UNKNOWN',
    'RD_KAFKA_CONF_INVALID',
    'RD_KAFKA_CONF_OK',
    'RD_KAFKA_MSG_PARTITIONER_RANDOM',
    'RD_KAFKA_MSG_PARTITIONER_CONSISTENT',
    'RD_KAFKA_LOG_PRINT',
    'RD_KAFKA_LOG_SYSLOG',
    'RD_KAFKA_LOG_SYSLOG_PRINT',
    'RD_KAFKA_RESP_ERR_NO_ERROR',
];

$RString = "";
foreach ($constants as $constant) {
    $var = constant($constant); // 获取常量的值
    $meaning = rd_kafka_err2str($var); // 获取kafka常量的意义
    $RString .= <<<EDO
    
// {$meaning}
defined('{$constant}') or define('{$constant}', {$var});

EDO;
}

echo $RString;

